CrudDemo/Controllers/EmployeementController.cs
using DataLayerLogic;
using DomainLayer.Model;
using DomainLayer.Repository;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using City = DataLayerLogic.City;
using CrudDemoDBEntities = DataLayerLogic.CrudDemoDBEntities;
using Department = DataLayerLogic.Department;

namespace CrudDemo.Controllers
{
    public class EmployeementController : Controller
    {
        private IEmployeeRepository _repo;
        public EmployeementController(IEmployeeRepository repo)
        {
            _repo = repo;
        }
        // GET: Employeement
        public ActionResult Index()
        {
            return View(_repo.GetAllEmployees(1));
        }
        [HttpPost]
        public ActionResult Index(int currentPageIndex)
        {
            return View(_repo.GetAllEmployees(1));
        }


        public ActionResult CreateEdit(int EmployeeId = 0)
        {
            var blogpost = _repo.GetEmployee(EmployeeId);
            //CrudDemoDBEntities db = new CrudDemoDBEntities();
            //List<City> citylist = db.Cities.ToList();
            //ViewBag.cityList = new SelectList(citylist, "CityId", "CityName");
            ViewBag.cityList = blogpost.CitiesList;
            return View(blogpost);
            //CrudDemoDBEntities db = new CrudDemoDBEntities();

            //List<SelectListItem> listOfDeparts = new List<SelectListItem>();
            //foreach (Department dept in db.Departments)
            //{
            //    SelectListItem selectList = new SelectListItem()
            //    {
            //        Text = dept.DepartmentName,
            //        Value = dept.DepartmentId.ToString(),
            //        Selected = dept.IsActive
            //    };
            //    listOfDeparts.Add(selectList);
            //}
            //EmployeeViewModel customerModel = new EmployeeViewModel();
            //customerModel.Departs = listOfDeparts;

            //List<City> citylist = db.Cities.ToList();
            //ViewBag.cityList = new SelectList(citylist, "CityId", "CityName");

            //if (EmployeeId > 0)
            //{
            //    //Employee emp = from x in db.Employees
            //    //               join y in db.Ci on x.EmpId equals y.Countryid into ps
            //    //               from p in ps
            //    //               select new { x.is, x.name, x.countryid, p.countryname }

            //    Employee emp = db.Employees.SingleOrDefault(x => x.EmpId == EmployeeId && x.IsActive == true);
            //    customerModel.EmpId = emp.EmpId;
            //    customerModel.DepartmentId = emp.DepartmentId;
            //    customerModel.Name = emp.Name;
            //    customerModel.Address = emp.Address;

            //    customerModel.Gender = emp.Gender;
            //    customerModel.DOB = emp.DOB;
            //    customerModel.CityId = emp.CityId;
            //    customerModel.IsActive = emp.IsActive;

            //}
            //return View(customerModel);
        }

        [HttpPost]
        public ActionResult CreateEdit(EmployeeViewModel model)
        {
            CrudDemoDBEntities db = new CrudDemoDBEntities();
            //List<Department> deptlist = db.Departments.ToList();
            //ViewBag.DepartmentList = new SelectList(deptlist, "DepartmentId", "DepartmentName");

            //List<City> citylist = db.Cities.ToList();
            //ViewBag.cityList = new SelectList(citylist, "CityId", "CityName");
            if (ModelState.IsValid)
            {
                _repo.CreateEmp(model);
                return RedirectToAction("Index");
            }

            return View(model);
            //try
            //{
            //    CrudDemoDBEntities db = new CrudDemoDBEntities();
            //    List<Department> deptlist = db.Departments.ToList();
            //    ViewBag.DepartmentList = new SelectList(deptlist, "DepartmentId", "DepartmentName");

            //    List<City> citylist = db.Cities.ToList();
            //    ViewBag.cityList = new SelectList(citylist, "CityId", "CityName");

            //    if (model.EmpId > 0)
            //    {
            //        //update
            //        Employee emp = db.Employees.SingleOrDefault(x => x.EmpId == model.EmpId && x.IsActive == true);
            //        emp.Name = model.Name;
            //        emp.Gender = model.Gender;
            //        emp.DOB = model.DOB;
            //        emp.Address = model.Address;
            //        emp.CityId = model.CityId;
            //        emp.DepartmentId = model.DepartmentId;
            //        emp.IsActive = model.IsActive;
            //        db.SaveChanges();


            //        //Employee emp = new Employee();
            //        //emp.Address = model.Address;
            //        //emp.Name = model.Name;
            //        //emp.DepartmentId = model.DepartmentId;

            //        //db.Employees.Add(emp);
            //        //db.SaveChanges();

            //        //int latestEmpId = emp.EmployeeId;


            //        //Site site = new Site();
            //        //site.SiteName = model.SiteName;
            //        //site.EmployeeId = latestEmpId;

            //        //db.Sites.Add(site);
            //        //db.SaveChanges();

            //    }
            //    else
            //    {
            //        //Insert
            //        Employee emp = new Employee();
            //        emp.Name = model.Name;
            //        emp.Gender = model.Gender;
            //        emp.DOB = model.DOB;
            //        emp.Address = model.Address;
            //        emp.CityId = model.CityId;

            //        emp.DepartmentId = model.DepartmentId;
            //        emp.IsActive = model.IsActive;
            //        db.Employees.Add(emp);
            //        db.SaveChanges();

            //    }
            //    return View(model);

            //}
            //catch (Exception ex)
            //{

            //    throw ex;
            //}

        }

        public ActionResult DeleteEmployee(int EmployeeId)
        {
            _repo.DeleteEmp(EmployeeId);
            return RedirectToAction("Index");

        }
    }
}

CrudDemo/Views/Employeement/CreateEdit.cshtml
@model DomainLayer.Model.EmployeeViewModel
@{
    /**/

    /**/

    ViewBag.Title = "CreateEdit";
}


@section Scripts {
    @Styles.Render("~/bundles/jquery")
    @Scripts.Render("~/Content/css")


    @Scripts.Render("~/bundles/jqueryui")
    @Styles.Render("~/Content/cssjqryUi")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[type=datetime]').datepicker({
                //dateFormat: "dd/MM/yy",
                format: 'dd/mm/yyyy',
                changeMonth: true,
                changeYear: true,
                yearRange: "-60:+0",
                maxDate: new Date()
            });

        });
    </script>

}

<h2>Create</h2>

@using (Html.BeginForm("CreateEdit", "Employeement", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Employees</h4>
        <hr />
        @Html.HiddenFor(x => x.EmpId)
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@
        <div class="form-group">
            @Html.LabelFor(x => x.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButton("Gender", 1)Male
                @Html.RadioButton("Gender", 2)Female
                @*@Html.TextBoxFor(x => x.Email, new { @class = "form-control" })*@
                @Html.ValidationMessageFor(x => x.Gender, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.DOB, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control", placeholder = "Employee Date Of Birth", @readonly = "true" } })
                @*@Html.TextBoxFor(x => x.DOB, new { htmlAttributes = new { @class = "form-control", placeholder = "Employee Date Of Birth", @readonly = "true" } })*@
                @Html.ValidationMessageFor(x => x.DOB, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">City</label>
            @*@Html.LabelFor(x => x.CityId, new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.CityId, ViewBag.cityList as SelectList, "--select--", new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.CityId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Department</label>
            <div class="col-md-10">
                @Html.ListBoxFor(x => x.SelectedDeparts, Model.Departs)
                @*@Html.DropDownListFor(x => x.DepartmentId, ViewBag.DepartmentList as SelectList, "--select--", new { @class = "form-control" })*@
                @Html.ValidationMessageFor(x => x.DepartmentId, "", new { @class = "text-danger" })



            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(x => x.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.CheckBoxFor(x => x.IsActive, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CrudDemo/Views/Employeement/Index.cshtml
@model DomainLayer.Model.EmployeeViewModel
@{
    ViewBag.Title = "Index";
    Layout = null;
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css" rel="stylesheet" />


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 10pt;
        }

        table {
            border: 1px solid #ccc;
            border-collapse: collapse;
            background-color: #fff;
        }

            table th {
                background-color: #B8DBFD;
                color: #333;
                font-weight: bold;
            }

            table th, table td {
                padding: 5px;
                border: 1px solid #ccc;
            }

            table, table table td {
                border: 0px solid #ccc;
            }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("Index", "Test", FormMethod.Post))
        {
            <h4>Customers</h4>
            <hr />
            <p class="add-btn">
                @Html.ActionLink("Add", "CreateEdit", "Employeement", null, new { @class = "btn btn-primary" })
            </p>
            if (Model.EMployees != null)
            {
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Action</th>
                        @*<th>City</th>
                            <th>Country</th>*@
                    </tr>
                    @foreach (var customer in Model.EMployees)
                    {
                        <tr>
                            <td>@customer.Name</td>
                            <td>@customer.Address</td>
                            <td>
                                @Html.ActionLink("EDIT", "CreateEdit", "Employeement", new { EmployeeId = customer.EmpId }, new { })||
                                @*<a onclick="return confirm('Do you want to Delete?')" href="@Url.Action("DeleteEmployee","Test",new {EmployeeId = customer.EmpId})">Delete</a> ||*@

                                @Html.ActionLink("Delete", "DeleteEmployee", "Employeement", new { EmployeeId = customer.EmpId }, new { onclick = "return confirm('Do you want to Delete?')" })
                                @*<a href="@Url.Action("CreateEdit ","Test ",new {EmployeeId= customer.EmpId  })">Edit</a>*@
                            </td>
                            @*<td>@customer.City</td>
                                <td>@customer.Country</td>*@
                        </tr>
                    }

                </table>
                <br />
                <table cellpadding="0" cellspacing="0">
                    <tr>
                        @for (int i = 1; i <= Model.PageCount; i++)
                        {
                            <td>
                                @if (i != Model.CurrentPageIndex)
                                {
                                    <a href="javascript:PagerClick(@i);">@i</a>
                                }
                                else
                                {
                                    <span>@i</span>
                                }
                            </td>
                        }
                    </tr>
                </table>
                <input type="hidden" id="hfCurrentPageIndex" name="currentPageIndex" />
            }
        }
        <script type="text/javascript">
            function PagerClick(index) {
                document.getElementById("hfCurrentPageIndex").value = index;
                document.forms[0].submit();
            }
        </script>
    </div>
</body>
</html>